services:
  accounts:
    image: "zeromr2010/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microbank_net
  loans:
    image: "zeromr2010/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microbank_net
  cards:
    image: "zeromr2010/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microbank_net

# defined network for internal communication between all 3 services
networks:
  microbank_net:
    driver: "bridge"